name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4  

      - name: Setup Node
        uses: actions/setup-node@v4  
        with:
          node-version: '20'  

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Create 404.html for React Router
        run: cp ./dist/index.html ./dist/404.html

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4  
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4 
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist