name: Deploy

on:
  push:
    branches:
      - main  # Ou 'master', dependendo da sua branch padrão

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Ou '18' para uma versão mais estável

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Create 404.html for React Router
        run: cp ./dist/index.html ./dist/404.html

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Ou 'master', dependendo da sua branch padrão

    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist